title: SproutBox Gaming
description: Game Reviews, Guides & More
theme: cayman

  
collections:
  posts:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

include:
  - public


