title: SproutBox Gaming
description: Game Reviews, Guides & More

remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  
collections:
  posts:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

include:
  - public


