title: SproutBox Gaming
description: Game Reviews, Guides & More
url: "https://sproutbox-gaming.com"
baseurl: "" # root path

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

include:
  - public
  - assets



